version: '3.7'
services:
  nas:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run test
    environment:
      NODE_ENV: test
      STORAGE_PATH: /tmp
    volumes:
      - .:/src
    ports:
      - "4000:3000"
